name: Build and Push Docker Image to Docker Hub and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        npm install
        npm ci 

    - name: build
      run: |
        npm run build
        npm run test
  build:
    runs-on: ubuntu-latest
    needs: [build_test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build . -t tailier/test:latest
          docker push tailier/test:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull tailier/test:latest
            docker stop container-name || true
            docker rm container-name || true
            docker run --name container-name -d -p 80:80 tailier/test:latest
